ALTER TABLE BSRC ADD COLUMN setting_physicaltherapy enum('office/clinic','home','daycare/preschool','other','not_answered');
ALTER TABLE BSRC ADD COLUMN setting_speechlangtherapy enum('office/clinic','home','daycare/preschool','other','not_answered');
ALTER TABLE BSRC ADD COLUMN setting_behaviorintervention enum('office/clinic','home','daycare/preschool','other','not_answered');
ALTER TABLE BSRC ADD COLUMN setting_otheroptions enum('office/clinic','home','daycare/preschool','other','not_answered');
ALTER TABLE BSRC ADD COLUMN servicetype_behaviorintervention enum('yes','no','not_answered');
ALTER TABLE BSRC CHANGE avg_occupationaltherapy avg_occupationaltherapy decimal(10,0);
ALTER TABLE BSRC DROP COLUMN avg_physicaltherapy_other;
ALTER TABLE BSRC DROP COLUMN avg_physicaltherapy_other_status;
ALTER TABLE BSRC ADD COLUMN avg_physicaltherapy decimal(10,0);
ALTER TABLE BSRC ADD COLUMN avg_physicaltherapy_status enum ('not_answered');
ALTER TABLE BSRC DROP COLUMN avg_speechlangtherapy_other;
ALTER TABLE BSRC DROP COLUMN avg_speechlangtherapy_other_status;
ALTER TABLE BSRC ADD avg_speechlangtherapy decimal(10,0);
ALTER TABLE BSRC ADD avg_speechlangtherapy_status enum ('not_answered');
ALTER TABLE BSRC DROP COLUMN avg_behaviorintervention_other;
ALTER TABLE BSRC ADD avg_behaviorintervention decimal(10,0);
ALTER TABLE BSRC ADD avg_behaviorintervention_status enum ('not_answered');
ALTER TABLE BSRC CHANGE avg_other avg_other decimal(10,0);
ALTER TABLE BSRC CHANGE q9_continue_nextyr q9_continue_nextyr enum('yes','no','not_applicable','not_answered');
