ALTER TABLE BSRC CHANGE startdate_occupationaltherapy startdate_occupationaltherapy_date date;
ALTER TABLE BSRC CHANGE startdate_physicaltherapy startdate_physicaltherapy_date date;
ALTER TABLE BSRC CHANGE startdate_speechlangtherapy startdate_speechlangtherapy_date date;
ALTER TABLE BSRC CHANGE startdate_other startdate_other_date date;
ALTER TABLE BSRC CHANGE continue_occupationaltherapy_stop continue_occupationaltherapy_stop_date date;
ALTER TABLE BSRC CHANGE continue_physicaltherapy_stop continue_physicaltherapy_stop_date date;
ALTER TABLE BSRC CHANGE continue_speechlangtherapy_stop continue_speechlangtherapy_stop_date date;
ALTER TABLE BSRC CHANGE continue_other_stop continue_other_stop_date date;
