CREATE TABLE `BSRC` (
`CommentID` varchar(255) NOT NULL default '',

                          `UserID` varchar(255) default NULL,

                          `Examiner` varchar(255) default NULL,

                          `Testdate` timestamp NOT NULL,

                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`date_lastVisit_date` date default NULL,
`date_lastVisit_date_status` enum('not_answered') default NULL,
`q1_earlyintervention_birthtothreeprg` enum('no','yes','not_answered') default NULL,
`q2_receive_earlyintervention_birthtothreeprg` enum('no','yes','not_answered') default NULL,
`hrs_earlyintervention_birthtothreeprg` varchar(255) default NULL,
`hrs_earlyintervention_birthtothreeprg_status` enum('not_answered') default NULL,
`total_earlyintervention_birthtothreeprg` varchar(255) default NULL,
`total_earlyintervention_birthtothreeprg_status` enum('not_answered') default NULL,
`q3_communityact` enum('no','yes','not_answered') default NULL,
`q4_participate_social` enum('no','yes','not_answered') default NULL,
`q5_service_delay` enum('no','yes','not_answered') default NULL,
`servicetype_occupationaltherapy` enum('no','yes','not_answered') default NULL,
`startdate_occupationaltherapy` date default NULL,
`continue_occupationaltherapy` enum('no','yes','not_answered') default NULL,
`stopdate_occupationaltherapy` date default NULL,
`indgrp_occupationaltherapy` enum('individual','group','not_answered') default NULL,
`setting_occupationaltherapy` enum('office_clinic','home','daycare_preschool','other','not_answered') default NULL,
`avg_occupationaltherapy` varchar(255) default NULL,
`avg_occupationaltherapy_status` enum('not_answered') default NULL,
`servicetype_physicaltherapy` enum('no','yes','not_answered') default NULL,
`startdate_physicaltherapy` date default NULL,
`continue_physicaltherapy` enum('no','yes','not_answered') default NULL,
`stopdate_physicaltherapy` date default NULL,
`indgrp_physicaltherapy` enum('individual','group','not_answered') default NULL,
`setting_physicaltherapy` enum('office_clinic','home','daycare_preschool','other','not_answered') default NULL,
`avg_physicaltherapy` varchar(255) default NULL,
`avg_physicaltherapy_status` enum('not_answered') default NULL,
`servicetype_speechlangtherapy` enum('no','yes','not_answered') default NULL,
`startdate_speechlangtherapy` date default NULL,
`continue_speechlangtherapy` enum('no','yes','not_answered') default NULL,
`stopdate_speechlangtherapy` date default NULL,
`indgrp_speechlangtherapy` enum('individual','group','not_answered') default NULL,
`setting_speechlangtherapy` enum('office_clinic','home','daycare_preschool','other','not_answered') default NULL,
`avg_speechlangtherapy` varchar(255) default NULL,
`avg_speechlangtherapy_status` enum('not_answered') default NULL,
`servicetype_behaviorintervention` enum('no','yes','not_answered') default NULL,
`startdate_behaviorintervention` date default NULL,
`continue_behaviorintervention` enum('no','yes','not_answered') default NULL,
`stopdate_behaviorintervention` date default NULL,
`indgrp_behaviorintervention` enum('individual','group','not_answered') default NULL,
`setting_behaviorintervention` enum('office_clinic','home','daycare_preschool','other','not_answered') default NULL,
`avg_behaviorintervention` varchar(255) default NULL,
`avg_behaviorintervention_status` enum('not_answered') default NULL,
`servicetype_other` enum('no','yes','not_answered') default NULL,
`startdate_other` date default NULL,
`continue_other` enum('no','yes','not_answered') default NULL,
`stopdate_other` date default NULL,
`indgrp_other` enum('individual','group','not_answered') default NULL,
`setting_other` enum('office_clinic','home','daycare_preschool','other','not_answered') default NULL,
`avg_other` varchar(255) default NULL,
`avg_other_status` enum('not_answered') default NULL,
`q6_avgperweek_A` varchar(255) default NULL,
`q6_avgperweek_A_status` enum('not_answered') default NULL,
`q6_avgperweek_B` varchar(255) default NULL,
`q6_avgperweek_B_status` enum('not_answered') default NULL,
`q7_alt_therapy` enum('no','yes','not_answered') default NULL,
`q7_alt_therapy_specify` text default NULL,
`q7_alt_therapy_specify_status` enum('not_answered') default NULL,
`q8_medical_pharma` enum('no','yes','not_answered') default NULL,
`q8_medical_pharma_specify` text default NULL,
`q8_medical_pharma_specify_status` enum('not_answered') default NULL,
`q9_continue_nextyr` enum('no','yes','na','not_answered') default NULL,
`q10_therapyoptions` enum('speech','occupational','physical','behavior_intervention','other','not_answered') default NULL,
`general_comments` text default NULL,
`general_comments_status` enum('not_answered') default NULL,
`other_comments` text default NULL,
`other_comments_status` enum('not_answered') default NULL,
PRIMARY KEY  (`CommentID`)

              );
