ALTER TABLE CBCL DROP COLUMN q100_otherproblems;
ALTER TABLE CBCL DROP COLUMN q100_otherproblems_status;
ALTER TABLE CBCL ADD COLUMN q100_otherproblems_1 text;
ALTER TABLE CBCL ADD COLUMN q100_otherproblems_1_status enum('not_answered');
ALTER TABLE CBCL ADD COLUMN q100_otherproblems_1_option enum('0_not_true','1_somewhat_or_sometimes_true','2_very_true_or_often_true','not_answered');
ALTER TABLE CBCL ADD COLUMN q100_otherproblems_2 text;
ALTER TABLE CBCL ADD COLUMN q100_otherproblems_2_status enum('not_answered');
ALTER TABLE CBCL ADD COLUMN q100_otherproblems_2_option enum('0_not_true','1_somewhat_or_sometimes_true','2_very_true_or_often_true','not_answered' );
ALTER TABLE CBCL ADD COLUMN q100_otherproblems_3 text;
ALTER TABLE CBCL ADD COLUMN q100_otherproblems_3_status enum('not_answered');
ALTER TABLE CBCL ADD COLUMN q100_otherproblems_3_option enum('0_not_true','1_somewhat_or_sometimes_true','2_very_true_or_often_true','not_answered' );
ALTER TABLE CBCL ADD COLUMN child_illness enum('yes','no');
ALTER TABLE CBCL ADD COLUMN best_things text;
ALTER TABLE CBCL ADD COLUMN best_things_status enum('not_answered');
ALTER TABLE CBCL ADD COLUMN most_concern text;
ALTER TABLE CBCL ADD COLUMN most_concern_status enum('not_answered');
ALTER TABLE CBCL ADD COLUMN describe_illness text;
ALTER TABLE CBCL ADD COLUMN describe_illness_status enum('not_answered');
ALTER TABLE CBCL ADD COLUMN parent_mostconcern_4 enum('q76_speech','q77_preoccupied','q78_stomachaches','q79_rapidshifts','q80_strange','q81_stubborn','q82_suddenchange','q83_sulks','q84_talksleep','q85_tantrum','q86_neatconcern','q87_toofearful','q88_uncoop','q89_underactive','q90_unhappy','q91_loud','q92_upsetnew','q93_vomit','q94_wakesoften','q95_wander','q96_wantattention','q97_whining','q98_withdrawn', 'q99_worries','q100_otherproblems_1','q100_otherproblems_2','q100_otherproblems_3','not_answered');
ALTER TABLE CBCL ADD COLUMN parent_mostconcern_1 enum('q1_aches','q2_young','q3_afraid','q4_eye','q5_attention','q6_hyperactive','q7_out','q8_wait','q9_chew','q10_dependent','q11_help','q12_constipated','q13_cries','q14_cruel','q15_defiant','q16_demands','q17_destroy','q18_destroy_other','q19_diarrhea','q20_disobedient','q21_routine','q22_sleepalone','q23_answer','q24_eat','q24_getalong','not_answered');
ALTER TABLE CBCL ADD COLUMN parent_mostconcern_2 enum('q26_fun','q27_guilty','q28_home','q29_frustrated','q30_jealous','q31_eatdrink','q32_fear','q33_feelings','q34_accident','q35_fights','q36_getsinto','q37_upset','q38_sleeptrouble','q39_headaches','q40_hits','q41_breath','q42_hurts','q43_lookunhappy','q44_angry','q45_nausea','q46_nervmovement','q47_nervous','q48_nightmates','q49_overeating','q50_overtired','not_answered');
ALTER TABLE CBCL ADD COLUMN parent_mostconcern_3 enum('q51_panic','q52_painbowel','q53_attack','q54_picks','q55_sex','q56_clumsy','q57_eyeprob','q58_punishment','q59_shifts','q60_skin','q61_refuseeat','q62_refuseplay','q63_rocks','q64_resbed','q65_restoilet','q66_screams','q67_unresponsive','q68_selfconscious','q69_selfish','q70_litaffection','q71_litinterest','q72_litfear','q73_shy','q74_sleepless','q75_bowelplay','not_answered');
