ALTER TABLE EARLI_interview_PART_4 CHANGE COLUMN `mother_id_status` `mother_id_status` enum('not_answered') default NULL;
ALTER TABLE EARLI_interview_PART_4 CHANGE COLUMN `interviewer_status` `interviewer_status` enum('not_answered') default NULL;
ALTER TABLE EARLI_interview_PART_4 CHANGE COLUMN `interview_date_date` `interview_date_date` date default NULL;
ALTER TABLE EARLI_interview_PART_4 ADD COLUMN `interview_date_date_status` enum('not_answered') default NULL;
ALTER TABLE EARLI_interview_PART_4 CHANGE COLUMN `interview_time` `interview_time` enum('1','2','3','4','5','6','7','8','9','10','11','12','not_answered') default NULL;
ALTER TABLE EARLI_interview_PART_4 CHANGE COLUMN `AMPM_top` `AMPM_top` enum('AM','PM','not_answered') default NULL;
ALTER TABLE EARLI_interview_PART_4 CHANGE COLUMN `q8_383other` `q8_383other` text default NULL;
ALTER TABLE EARLI_interview_PART_4 CHANGE COLUMN `q8_383other_status` `q8_383other_status` enum('88_refused','99_do_not_know','not_answered') default NULL;
ALTER TABLE EARLI_interview_PART_4 ADD COLUMN `interview_end_date_date` date default NULL;
ALTER TABLE EARLI_interview_PART_4 ADD COLUMN `interview_end_date_date_status` enum('not_answered') default NULL;
ALTER TABLE EARLI_interview_PART_4 CHANGE COLUMN `interview_end_time` `interview_end_time` enum('1','2','3','4','5','6','7','8','9','10','11','12','not_answered') default NULL;
ALTER TABLE EARLI_interview_PART_4 CHANGE COLUMN `AMPM_bottom` `AMPM_bottom` enum('AM','PM','not_answered') default NULL;
ALTER TABLE EARLI_interview_PART_4 CHANGE COLUMN `interviewer_notes_status` `interviewer_notes_status` enum('not_answered') default NULL;
