/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `edi2`
--

DROP TABLE IF EXISTS `edi2`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `edi2` (
  `CommentID` varchar(255) NOT NULL DEFAULT '',
  `UserID` varchar(255) DEFAULT NULL,
  `Examiner` varchar(255) DEFAULT NULL,
  `Testdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL DEFAULT 'Incomplete',
  `Date_taken` date DEFAULT NULL,
  `Candidate_Age` varchar(255) DEFAULT NULL,
  `Window_Difference` int(11) DEFAULT NULL,
  `score_0_3_total_symptoms` varchar(255) DEFAULT NULL,
  `score_0_3_regulatory` varchar(255) DEFAULT NULL,
  `score_4_6_total_symptoms` varchar(255) DEFAULT NULL,
  `score_4_6_regulatory` varchar(255) DEFAULT NULL,
  `score_4_6_social` varchar(255) DEFAULT NULL,
  `score_7_9_total_symptoms` varchar(255) DEFAULT NULL,
  `score_7_9_regulatory` varchar(255) DEFAULT NULL,
  `score_7_9_social` varchar(255) DEFAULT NULL,
  `score_7_9_communication` varchar(255) DEFAULT NULL,
  `score_10_12_total_symptoms` varchar(255) DEFAULT NULL,
  `score_10_12_regulatory` varchar(255) DEFAULT NULL,
  `score_10_12_social` varchar(255) DEFAULT NULL,
  `score_10_12_communication` varchar(255) DEFAULT NULL,
  `score_10_12_repetitive_behaviour` varchar(255) DEFAULT NULL,
  `score_13_15_total_symptoms` varchar(255) DEFAULT NULL,
  `score_13_15_regulatory` varchar(255) DEFAULT NULL,
  `score_13_15_social` varchar(255) DEFAULT NULL,
  `score_13_15_communication` varchar(255) DEFAULT NULL,
  `score_13_15_repetitive_behaviour` varchar(255) DEFAULT NULL,
  `score_16_18_total_symptoms` varchar(255) DEFAULT NULL,
  `score_16_18_regulatory` varchar(255) DEFAULT NULL,
  `score_16_18_social` varchar(255) DEFAULT NULL,
  `score_16_18_communication` varchar(255) DEFAULT NULL,
  `score_16_18_repetitive_behaviour` varchar(255) DEFAULT NULL,
  `score_19_21_total_symptoms` varchar(255) DEFAULT NULL,
  `score_19_21_regulatory` varchar(255) DEFAULT NULL,
  `score_19_21_social` varchar(255) DEFAULT NULL,
  `score_19_21_communication` varchar(255) DEFAULT NULL,
  `score_19_21_repetitive_behaviour` varchar(255) DEFAULT NULL,
  `score_22_24_total_symptoms` varchar(255) DEFAULT NULL,
  `score_22_24_regulatory` varchar(255) DEFAULT NULL,
  `score_22_24_social` varchar(255) DEFAULT NULL,
  `score_22_24_communication` varchar(255) DEFAULT NULL,
  `score_22_24_repetitive_behaviour` varchar(255) DEFAULT NULL,
  `EDI1` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI2` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI3` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI4` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI5` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI6` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI7` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI8` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI8ot` text,
  `EDI8ot_status` enum('not_answered') DEFAULT NULL,
  `EDI9` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI10` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI11` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI12` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI13` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI14` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI15` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI16` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI17` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI18` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI19` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI19ot` text,
  `EDI19ot_status` enum('not_answered') DEFAULT NULL,
  `EDI20` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI21` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI22` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI23` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI24` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI25` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI26` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI27` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI28` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI29` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI30` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI31` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI32` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI33` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI33ot` text,
  `EDI33ot_status` enum('not_answered') DEFAULT NULL,
  `EDI34` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI35` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI36` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI37` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI38` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI39` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI40` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI41` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI42` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI43` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI44` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI45` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI45ot` text,
  `EDI45ot_status` enum('not_answered') DEFAULT NULL,
  `EDI46` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI47` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI48` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI49` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI50` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI51` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI52` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI53` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI54` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI55` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI56` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI57` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI58` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI58ot` text,
  `EDI58ot_status` enum('not_answered') DEFAULT NULL,
  `EDI59` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI60` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI61` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI62` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI63` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI64` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI65` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI66` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI67` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI68` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI69` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI70` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI70ot` text,
  `EDI70ot_status` enum('not_answered') DEFAULT NULL,
  `EDI71` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI72` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI73` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI74` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI75` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI76` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI77` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI78` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI79` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI80` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI81` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI82` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI82ot` text,
  `EDI82ot_status` enum('not_answered') DEFAULT NULL,
  `EDI83` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI84` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI85` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI86` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI87` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI88` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI89` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI90` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI91` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI92` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI93` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI94` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI95` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI96` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `EDI96ot` text,
  `EDI96ot_status` enum('not_answered') DEFAULT NULL,
  `inj` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `inj_month` varchar(255) DEFAULT NULL,
  `inj_month_status` enum('not_answered') DEFAULT NULL,
  `dear` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `dear_month` varchar(255) DEFAULT NULL,
  `dear_month_status` enum('not_answered') DEFAULT NULL,
  `conf` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `conf_month` varchar(255) DEFAULT NULL,
  `conf_month_status` enum('not_answered') DEFAULT NULL,
  `legl` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `legl_month` varchar(255) DEFAULT NULL,
  `legl_month_status` enum('not_answered') DEFAULT NULL,
  `emp` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `emp_month` varchar(255) DEFAULT NULL,
  `emp_month_status` enum('not_answered') DEFAULT NULL,
  `crim` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `crim_month` varchar(255) DEFAULT NULL,
  `crim_month_status` enum('not_answered') DEFAULT NULL,
  `other_1` varchar(255) DEFAULT NULL,
  `other_1_status` enum('not_answered') DEFAULT NULL,
  `other_1_code` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `other_1_month` varchar(255) DEFAULT NULL,
  `other_1_month_status` enum('not_answered') DEFAULT NULL,
  `other_2` varchar(255) DEFAULT NULL,
  `other_2_status` enum('not_answered') DEFAULT NULL,
  `other_2_code` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `other_2_month` varchar(255) DEFAULT NULL,
  `other_2_month_status` enum('not_answered') DEFAULT NULL,
  `comnt` text,
  `comnt_status` enum('not_answered') DEFAULT NULL,
  `Visit_Range` varchar(25) DEFAULT NULL,
  `bir` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `dea` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `divorce` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `mar` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `mov` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `tem` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `per` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `chc` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `chs` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `sei` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `hea` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `othi` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `hifv` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `hosp` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `mill` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  `div` enum('0_no','1_possible','2_definite','not_answered') DEFAULT NULL,
  PRIMARY KEY (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;


