CREATE TABLE `LENA_DataTrackingForm` (
`CommentID` varchar(255) NOT NULL default '',
                          `UserID` varchar(255) default NULL,
                          `Examiner` varchar(255) default NULL,
                          `Testdate` timestamp NOT NULL,
                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`datecompleted` date default NULL,
`family_participate` enum('yes','no') default NULL,
`reasonsdecline` varchar(255) default NULL,
`number_session` enum('1','2','3','4') default NULL,
`duration_session1` enum('full_day','less_16hrs','notused_del') default NULL,
`comments_session1` text default NULL,
`comments_session1_status` enum('not_answered') default NULL,
`duration_session2` enum('full_day','less_16hrs','notused_del') default NULL,
`comments_session2` text default NULL,
`comments_session2_status` enum('not_answered') default NULL,
`duration_session3` enum('full_day','less_16hrs','notused_del') default NULL,
`comments_session3` text default NULL,
`comments_session3_status` enum('not_answered') default NULL,
`duration_session4` enum('full_day','less_16hrs','notused_del') default NULL,
`comments_session4` text default NULL,
`File_name` varchar(256) default NULL,
`File_type` varchar(256) default NULL,
`Data_dir` varchar(256) default NULL,
PRIMARY KEY  (`CommentID`)
              );
