ALTER TABLE med_recordsproband ADD COLUMN other_genetic_tests_completed_specify2 varchar(255);
ALTER TABLE med_recordsproband ADD COLUMN other_genetic_tests_completed_specify2_status enum('not_answered');
ALTER TABLE med_recordsproband ADD COLUMN other_genetic_tests_completed_specify3 varchar(255);
ALTER TABLE med_recordsproband ADD COLUMN other_genetic_tests_completed_specify3_status enum('not_answered');
ALTER TABLE med_recordsproband ADD COLUMN other_genetic_tests_completed_specify4 varchar(255);
ALTER TABLE med_recordsproband ADD COLUMN other_genetic_tests_completed_specify4_status enum('not_answered');
ALTER TABLE med_recordsproband ADD COLUMN other_genetic_tests_completed_specify5 varchar(255);
ALTER TABLE med_recordsproband ADD COLUMN other_genetic_tests_completed_specify5_status enum('not_answered');
ALTER TABLE med_recordsproband ADD COLUMN date_genetic_test2 date;
ALTER TABLE med_recordsproband ADD COLUMN date_genetic_test2_status enum('not_answered');
ALTER TABLE med_recordsproband ADD COLUMN date_genetic_test3 date;
ALTER TABLE med_recordsproband ADD COLUMN date_genetic_test3_status enum('not_answered');
ALTER TABLE med_recordsproband ADD COLUMN date_genetic_test4 date;
ALTER TABLE med_recordsproband ADD COLUMN date_genetic_test4_status enum('not_answered');
ALTER TABLE med_recordsproband ADD COLUMN date_genetic_test5 date;
ALTER TABLE med_recordsproband ADD COLUMN date_genetic_test5_status enum('not_answered');
ALTER TABLE med_records_proband ADD COLUMN Lastupdated_growthchart_date date;
ALTER TABLE med_records_proband ADD COLUMN Lastupdated_growthchart_date_status enum('not_answered') ;
ALTER TABLE med_records_proband ADD COLUMN Lastupdated_growthchart2_date date;
ALTER TABLE med_records_proband ADD COLUMN Lastupdated_growthchart2_date_status enum('not_answered') ;
