ALTER TABLE med_psych_hist CHANGE COLUMN q6_a_antibio_infections_when_taken q6_a_antibio_infections_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_b_acne_meds_when_taken q6_b_acne_meds_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_c_birth_control_meds_when_taken q6_c_birth_control_meds_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_d_antihypertensives_when_taken q6_d_antihypertensives_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_e_heart_cardiac_meds_when_taken q6_e_heart_cardiac_meds_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_f_ADD_meds_when_taken q6_f_ADD_meds_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_g_antiepilep_anti_seizure_when_taken q6_g_antiepilep_anti_seizure_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_h_diabetes_meds_when_taken q6_h_diabetes_meds_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_i_thyroid_meds_when_taken q6_i_thyroid_meds_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_j_antidepressants_when_taken q6_j_antidepressants_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_k_mood_stabs_anti_psychos_when_taken q6_k_mood_stabs_anti_psychos_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_l_tranquilizers_nerve_pills_when_taken q6_l_tranquilizers_nerve_pills_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_m_pain_killers_when_taken q6_m_pain_killers_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_n_sedatives_sleeping_pills_when_taken q6_n_sedatives_sleeping_pills_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_o_anti_inflam_immune_when_taken q6_o_anti_inflam_immune_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_p_treatment_for_HIV_when_taken q6_p_treatment_for_HIV_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_q_thalidomide_when_taken q6_q_thalidomide_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_r_misoprostol_when_taken q6_r_misoprostol_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q6_s_other_when_taken q6_s_other_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q8_a_drink_alcohol_when_taken q8_a_drink_alcohol_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q8_b_tobacco_when_taken q8_b_tobacco_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist ADD COLUMN q8_a1_drink_quantity enum('0','1_2','3_more','not_answered');
 ALTER TABLE med_psych_hist ADD COLUMN q8_a2_drink_max_week varchar(255);
 ALTER TABLE med_psych_hist ADD COLUMN q8_a2_drink_max_week_status enum('not_answered');
 ALTER TABLE med_psych_hist ADD COLUMN q8_b1_cigarette_perday enum ('0','5_10','10_more','not_answered');
 ALTER TABLE med_psych_hist CHANGE COLUMN q9_b_cocaine_crack_free_base_when_taken q9_b_cocaine_crack_free_base_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q9_c_heroin_when_taken q9_c_heroin_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q9_d_methadone_when_taken q9_d_methadone_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q9_e_amphet_stims_when_taken q9_e_amphet_stims_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q9_f_ecstasy_when_taken q9_f_ecstasy_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q9_g_hallucinogens_when_taken q9_g_hallucinogens_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q9_h_inhalants_when_taken q9_h_inhalants_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
 ALTER TABLE med_psych_hist CHANGE COLUMN q9_i_other_when_taken q9_i_other_when_taken enum('0_before','1_after','2_both','not_answered','3_breastfeeding');
ALTER TABLE med_psych_hist ADD COLUMN q13_neonatal_icu_reason varchar(255);
ALTER TABLE med_psych_hist ADD COLUMN q13_neonatal_icu_reason_status enum('not_answered');

