ALTER TABLE med_records_recruit ADD not_completed enum('complete','not_complete','other') DEFAULT NULL;
ALTER TABLE med_records_recruit ADD not_completed_other_specify varchar(255) DEFAULT NULL;
ALTER TABLE med_records_recruit ADD not_completed_other_specify_status enum('not_answered') DEFAULT NULL;
ALTER TABLE med_records_recruit ADD hearing_screening_date date DEFAULT NULL;
ALTER TABLE med_records_recruit ADD hearing_screening_date_status enum('not_answered') DEFAULT NULL;
ALTER TABLE med_records_recruit ADD vra varchar(255) DEFAULT NULL;
ALTER TABLE med_records_recruit ADD oae varchar(255) DEFAULT NULL;
ALTER TABLE med_records_recruit ADD tympanometry varchar(255) DEFAULT NULL;
ALTER TABLE med_records_recruit ADD other_method varchar(255) DEFAULT NULL;
ALTER TABLE med_records_recruit ADD other_method_specify varchar(255) DEFAULT NULL;
ALTER TABLE med_records_recruit ADD other_method_specify_status enum('not_answered') DEFAULT NULL;
ALTER TABLE med_records_recruit ADD test_results enum('normal_hearing','temporary_hearing_difficulty','equivocal_evaluation_results','permanent_abnormal_hearing','not_answered') DEFAULT NULL;
ALTER TABLE med_records_recruit ADD test_results_ear enum('left_ear','right_ear','bilateral','not_answered') DEFAULT NULL;
ALTER TABLE med_records_recruit ADD test_results_severity enum('partial','total','not_answered') DEFAULT NULL;
ALTER TABLE med_records_recruit ADD equivocal_evaluation_results_specify text;
ALTER TABLE med_records_recruit ADD equivocal_evaluation_results_specify_status enum('not_answered') DEFAULT NULL;
ALTER TABLE med_records_recruit ADD COLUMN Lastupdated_audiology_date date;
ALTER TABLE med_records_recruit ADD COLUMN Lastupdated_audiology_date_status enum('not_answered');
INSERT INTO instrument_subtests (Test_name,Subtest_name, Description,Order_number) VALUES ('med_records_recruit','med_records_recruit_page4','Audiology Report (IBIS2 only)',4);
