ALTER TABLE mri_parameter_form ADD COLUMN File_type VARCHAR(256) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN File_name VARCHAR(256) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN Data_dir VARCHAR(256) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN coordinate_system VARCHAR(256) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN normalization VARCHAR(256) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector0_x DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector0_y DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector0_z DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector1_x DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector1_y DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector1_z DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector2_x DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector2_y DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector2_z DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector3_x DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector3_y DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector3_z DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector4_x DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector4_y DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector4_z DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector5_x DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector5_y DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector5_z DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector6_x DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector6_y DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector6_z DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector7_x DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector7_y DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector7_z DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector8_x DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector8_y DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector8_z DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector9_x DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector9_y DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector9_z DECIMAL(20, 20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector10_x DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector10_y DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector10_z DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector11_x DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector11_y DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector11_z DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector12_x DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector12_y DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector12_z DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector13_x DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector13_y DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector13_z DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector14_x DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector14_y DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector14_z DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector15_x DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector15_y DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector15_z DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector16_x DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector16_y DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector16_z DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector17_x DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector17_y DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector17_z DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector18_x DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector18_y DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector18_z DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector19_x DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector19_y DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector19_z DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector20_x DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector20_y DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector20_z DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector21_x DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector21_y DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector21_z DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector22_x DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector22_y DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector22_z DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector23_x DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector23_y DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector23_z DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector24_x DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector24_y DECIMAL(20,20) NULL;
ALTER TABLE mri_parameter_form ADD COLUMN vector24_z DECIMAL(20,20) NULL;
