CREATE TABLE `peer_socialcontact` (
`CommentID` varchar(255) NOT NULL default '',

                          `UserID` varchar(255) default NULL,

                          `Examiner` varchar(255) default NULL,

                          `Testdate` timestamp NOT NULL,

                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`respondent` enum('mother','father','other') default NULL,
`respondent_other` varchar(255) default NULL,
`total_playmates` enum('1','2','3','4','5') default NULL,
`peer_initials_1` varchar(255) default NULL,
`peer_initials_2` varchar(255) default NULL,
`peer_initials_3` varchar(255) default NULL,
`peer_initials_4` varchar(255) default NULL,
`peer_initials_5` varchar(255) default NULL,
`know_1_2` enum ('yes','no','not_answered') default NULL,
`know_1_3` enum ('yes','no','not_answered') default NULL,
`know_1_4` enum ('yes','no','not_answered') default NULL,
`know_1_5` enum ('yes','no','not_answered') default NULL,
`know_2_3` enum ('yes','no','not_answered') default NULL,
`know_2_4` enum ('yes','no','not_answered') default NULL,
`know_2_5` enum ('yes','no','not_answered') default NULL,
`know_3_4` enum ('yes','no','not_answered') default NULL,
`know_3_5` enum ('yes','no','not_answered') default NULL,
`know_4_5` enum ('yes','no','not_answered') default NULL,
`age_yrs_playmate_1` enum('0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','refused_dontknow') default NULL,
`age_mos_playmate_1` enum('0','1','2','3','4','5','6','7','8','9','10','11','12','refused_dontknow') default NULL,
`gender_playmate_1` enum('boy','girl','refused_dontknow') default NULL,
`q1_number_playtimes_playmate1` varchar(255) default NULL,
`q2_avg_playtime_playmate1` varchar(255) default NULL,
`q3_related_playmate1` enum('cousins','neighbors','classmates','parent_friend_child','other','refused_dontknow') default NULL,
`q3_related_other_playmate1` varchar(255) default NULL,
`q4_playarea_playmate1` enum('mostly_your_home','mostly_playmate_home','equally_both','mostly_other','refused_dontknow') default NULL,
`q4_playarea_other_playmate1` varchar(255) default NULL,
`q5_proximity_playmate1` enum('walking_distance','short_drive','long_drive','refused_dontknow') default NULL,
`q6_sameschool_playmate1` enum('yes','no','refused_dontknow') default NULL,
`q7_samechildcare_playmate1` enum('yes','no','refused_dontknow') default NULL,
`q8_specialneeds_playmate1` enum('none','dont_know','autism','other_developmental_delay','speech_language_delay','other','refused_dontknow') default NULL,
`q8_specialneeds_other_playmate1` varchar(255) default NULL,
`q9_yourchild_like_playmate1` enum('really_likes','likes','pretty_neutral','just_tolerates','refused_dontknow') default NULL,
`q10_like_yourchild_playmate1` enum('really_likes','likes','pretty_neutral','just_tolerates','refused_dontknow') default NULL,
`q11_getalong_playmate1` enum('very_well','okay','not_very_well','refused_dontknow') default NULL,
`q12_leading_play_playmate1` enum('my_child','playmate','both','adult','refused_dontknow') default NULL,
`q13_typical_playtone_playmate1` enum('positive','neutral','negative','refused_dontknow') default NULL,
`q14_typical_excitement_playmate1` enum('very_excited','active','calm','refused_dontknow') default NULL,
`q15_num_conflicts_playmate1` enum('frequently','occasionally','rarely','refused_dontknow') default NULL,
`q16_disruptive_playmate1` enum('ends_play','major_disruption','minor_disruption','no_disruption','refused_dontknow') default NULL,
`q17_how_involved_playmate1` enum('lot_of_interaction','stay_close_no_interaction','dont_stay_close_or_interact','refused_dontknow') default NULL,
`q18_arrangeplay_you_playmate1` varchar(255) default NULL,
`q18_arrangeplay_yourchild_playmate1` varchar(255) default NULL,
`q18_arrangeplay_other_playmate1` varchar(255) default NULL,
`q19_arrange_contacts_playmate1` enum('very_difficult','somewhat_difficult','not_difficult','refused_dontknow') default NULL,
`q20_stress_monitorplay_playmate1` enum('very_stressful','somewhat_stressful','not_stressful','refused_dontknow') default NULL,
`q21_facililate_getalong_playmate1` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_participate_activity_playmate1` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_maintain_presence_playmate1` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_outofview_listen_playmate1` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_outofview_notlisten_playmate1` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_manage_emotions_playmate1` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_understand_rules_playmate1` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_understand_howtoplay_playmate1` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_startplay_playmate1` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_remain_inplay_playmate1` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_manage_conflicts_playmate1` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`age_yrs_playmate_2` enum('0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','refused_dontknow') default NULL,
`age_mos_playmate_2` enum('0','1','2','3','4','5','6','7','8','9','10','11','12','refused_dontknow') default NULL,
`gender_playmate_2` enum('boy','girl','refused_dontknow') default NULL,
`q1_number_playtimes_playmate2` varchar(255) default NULL,
`q2_avg_playtime_playmate2` varchar(255) default NULL,
`q3_related_playmate2` enum('cousins','neighbors','classmates','parent_friend_child','other','refused_dontknow') default NULL,
`q3_related_other_playmate2` varchar(255) default NULL,
`q4_playarea_playmate2` enum('mostly_your_home','mostly_playmate_home','equally_both','mostly_other','refused_dontknow') default NULL,
`q4_playarea_other_playmate2` varchar(255) default NULL,
`q5_proximity_playmate2` enum('walking_distance','short_drive','long_drive','refused_dontknow') default NULL,
`q6_sameschool_playmate2` enum('yes','no','refused_dontknow') default NULL,
`q7_samechildcare_playmate2` enum('yes','no','refused_dontknow') default NULL,
`q8_specialneeds_playmate2` enum('none','dont_know','autism','other_developmental_delay','speech_language_delay','other','refused_dontknow') default NULL,
`q8_specialneeds_other_playmate2` varchar(255) default NULL,
`q9_yourchild_like_playmate2` enum('really_likes','likes','pretty_neutral','just_tolerates','refused_dontknow') default NULL,
`q10_like_yourchild_playmate2` enum('really_likes','likes','pretty_neutral','just_tolerates','refused_dontknow') default NULL,
`q11_getalong_playmate2` enum('very_well','okay','not_very_well','refused_dontknow') default NULL,
`q12_leading_play_playmate2` enum('my_child','playmate','both','adult','refused_dontknow') default NULL,
`q13_typical_playtone_playmate2` enum('positive','neutral','negative','refused_dontknow') default NULL,
`q14_typical_excitement_playmate2` enum('very_excited','active','calm','refused_dontknow') default NULL,
`q15_num_conflicts_playmate2` enum('frequently','occasionally','rarely','refused_dontknow') default NULL,
`q16_disruptive_playmate2` enum('ends_play','major_disruption','minor_disruption','no_disruption','refused_dontknow') default NULL,
`q17_how_involved_playmate2` enum('lot_of_interaction','stay_close_no_interaction','dont_stay_close_or_interact','refused_dontknow') default NULL,
`q18_arrangeplay_you_playmate2` varchar(255) default NULL,
`q18_arrangeplay_yourchild_playmate2` varchar(255) default NULL,
`q18_arrangeplay_other_playmate2` varchar(255) default NULL,
`q19_arrange_contacts_playmate2` enum('very_difficult','somewhat_difficult','not_difficult','refused_dontknow') default NULL,
`q20_stress_monitorplay_playmate2` enum('very_stressful','somewhat_stressful','not_stressful','refused_dontknow') default NULL,
`q21_facililate_getalong_playmate2` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_participate_activity_playmate2` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_maintain_presence_playmate2` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_outofview_listen_playmate2` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_outofview_notlisten_playmate2` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_manage_emotions_playmate2` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_understand_rules_playmate2` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_understand_howtoplay_playmate2` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_startplay_playmate2` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_remain_inplay_playmate2` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_manage_conflicts_playmate2` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`age_yrs_playmate_3` enum('0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','refused_dontknow') default NULL,
`age_mos_playmate_3` enum('0','1','2','3','4','5','6','7','8','9','10','11','12','refused_dontknow') default NULL,
`gender_playmate_3` enum('boy','girl','refused_dontknow') default NULL,
`q1_number_playtimes_playmate3` varchar(255) default NULL,
`q2_avg_playtime_playmate3` varchar(255) default NULL,
`q3_related_playmate3` enum('cousins','neighbors','classmates','parent_friend_child','other','refused_dontknow') default NULL,
`q3_related_other_playmate3` varchar(255) default NULL,
`q4_playarea_playmate3` enum('mostly_your_home','mostly_playmate_home','equally_both','mostly_other','refused_dontknow') default NULL,
`q4_playarea_other_playmate3` varchar(255) default NULL,
`q5_proximity_playmate3` enum('walking_distance','short_drive','long_drive','refused_dontknow') default NULL,
`q6_sameschool_playmate3` enum('yes','no','refused_dontknow') default NULL,
`q7_samechildcare_playmate3` enum('yes','no','refused_dontknow') default NULL,
`q8_specialneeds_playmate3` enum('none','dont_know','autism','other_developmental_delay','speech_language_delay','other','refused_dontknow') default NULL,
`q8_specialneeds_other_playmate3` varchar(255) default NULL,
`q9_yourchild_like_playmate3` enum('really_likes','likes','pretty_neutral','just_tolerates','refused_dontknow') default NULL,
`q10_like_yourchild_playmate3` enum('really_likes','likes','pretty_neutral','just_tolerates','refused_dontknow') default NULL,
`q11_getalong_playmate3` enum('very_well','okay','not_very_well','refused_dontknow') default NULL,
`q12_leading_play_playmate3` enum('my_child','playmate','both','adult','refused_dontknow') default NULL,
`q13_typical_playtone_playmate3` enum('positive','neutral','negative','refused_dontknow') default NULL,
`q14_typical_excitement_playmate3` enum('very_excited','active','calm','refused_dontknow') default NULL,
`q15_num_conflicts_playmate3` enum('frequently','occasionally','rarely','refused_dontknow') default NULL,
`q16_disruptive_playmate3` enum('ends_play','major_disruption','minor_disruption','no_disruption','refused_dontknow') default NULL,
`q17_how_involved_playmate3` enum('lot_of_interaction','stay_close_no_interaction','dont_stay_close_or_interact','refused_dontknow') default NULL,
`q18_arrangeplay_you_playmate3` varchar(255) default NULL,
`q18_arrangeplay_yourchild_playmate3` varchar(255) default NULL,
`q18_arrangeplay_other_playmate3` varchar(255) default NULL,
`q19_arrange_contacts_playmate3` enum('very_difficult','somewhat_difficult','not_difficult','refused_dontknow') default NULL,
`q20_stress_monitorplay_playmate3` enum('very_stressful','somewhat_stressful','not_stressful','refused_dontknow') default NULL,
`q21_facililate_getalong_playmate3` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_participate_activity_playmate3` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_maintain_presence_playmate3` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_outofview_listen_playmate3` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_outofview_notlisten_playmate3` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_manage_emotions_playmate3` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_understand_rules_playmate3` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_understand_howtoplay_playmate3` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_startplay_playmate3` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_remain_inplay_playmate3` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_manage_conflicts_playmate3` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`age_yrs_playmate_4` enum('0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','refused_dontknow') default NULL,
`age_mos_playmate_4` enum('0','1','2','3','4','5','6','7','8','9','10','11','12','refused_dontknow') default NULL,
`gender_playmate_4` enum('boy','girl','refused_dontknow') default NULL,
`q1_number_playtimes_playmate4` varchar(255) default NULL,
`q2_avg_playtime_playmate4` varchar(255) default NULL,
`q3_related_playmate4` enum('cousins','neighbors','classmates','parent_friend_child','other','refused_dontknow') default NULL,
`q3_related_other_playmate4` varchar(255) default NULL,
`q4_playarea_playmate4` enum('mostly_your_home','mostly_playmate_home','equally_both','mostly_other','refused_dontknow') default NULL,
`q4_playarea_other_playmate4` varchar(255) default NULL,
`q5_proximity_playmate4` enum('walking_distance','short_drive','long_drive','refused_dontknow') default NULL,
`q6_sameschool_playmate4` enum('yes','no','refused_dontknow') default NULL,
`q7_samechildcare_playmate4` enum('yes','no','refused_dontknow') default NULL,
`q8_specialneeds_playmate4` enum('none','dont_know','autism','other_developmental_delay','speech_language_delay','other','refused_dontknow') default NULL,
`q8_specialneeds_other_playmate4` varchar(255) default NULL,
`q9_yourchild_like_playmate4` enum('really_likes','likes','pretty_neutral','just_tolerates','refused_dontknow') default NULL,
`q10_like_yourchild_playmate4` enum('really_likes','likes','pretty_neutral','just_tolerates','refused_dontknow') default NULL,
`q11_getalong_playmate4` enum('very_well','okay','not_very_well','refused_dontknow') default NULL,
`q12_leading_play_playmate4` enum('my_child','playmate','both','adult','refused_dontknow') default NULL,
`q13_typical_playtone_playmate4` enum('positive','neutral','negative','refused_dontknow') default NULL,
`q14_typical_excitement_playmate4` enum('very_excited','active','calm','refused_dontknow') default NULL,
`q15_num_conflicts_playmate4` enum('frequently','occasionally','rarely','refused_dontknow') default NULL,
`q16_disruptive_playmate4` enum('ends_play','major_disruption','minor_disruption','no_disruption','refused_dontknow') default NULL,
`q17_how_involved_playmate4` enum('lot_of_interaction','stay_close_no_interaction','dont_stay_close_or_interact','refused_dontknow') default NULL,
`q18_arrangeplay_you_playmate4` varchar(255) default NULL,
`q18_arrangeplay_yourchild_playmate4` varchar(255) default NULL,
`q18_arrangeplay_other_playmate4` varchar(255) default NULL,
`q19_arrange_contacts_playmate4` enum('very_difficult','somewhat_difficult','not_difficult','refused_dontknow') default NULL,
`q20_stress_monitorplay_playmate4` enum('very_stressful','somewhat_stressful','not_stressful','refused_dontknow') default NULL,
`q21_facililate_getalong_playmate4` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_participate_activity_playmate4` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_maintain_presence_playmate4` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_outofview_listen_playmate4` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_outofview_notlisten_playmate4` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_manage_emotions_playmate4` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_understand_rules_playmate4` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_understand_howtoplay_playmate4` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_startplay_playmate4` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_remain_inplay_playmate4` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_manage_conflicts_playmate4` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`age_yrs_playmate_5` enum('0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','refused_dontknow') default NULL,
`age_mos_playmate_5` enum('0','1','2','3','4','5','6','7','8','9','10','11','12','refused_dontknow') default NULL,
`gender_playmate_5` enum('boy','girl','refused_dontknow') default NULL,
`q1_number_playtimes_playmate5` varchar(255) default NULL,
`q2_avg_playtime_playmate5` varchar(255) default NULL,
`q3_related_playmate5` enum('cousins','neighbors','classmates','parent_friend_child','other','refused_dontknow') default NULL,
`q3_related_other_playmate5` varchar(255) default NULL,
`q4_playarea_playmate5` enum('mostly_your_home','mostly_playmate_home','equally_both','mostly_other','refused_dontknow') default NULL,
`q4_playarea_other_playmate5` varchar(255) default NULL,
`q5_proximity_playmate5` enum('walking_distance','short_drive','long_drive','refused_dontknow') default NULL,
`q6_sameschool_playmate5` enum('yes','no','refused_dontknow') default NULL,
`q7_samechildcare_playmate5` enum('yes','no','refused_dontknow') default NULL,
`q8_specialneeds_playmate5` enum('none','dont_know','autism','other_developmental_delay','speech_language_delay','other','refused_dontknow') default NULL,
`q8_specialneeds_other_playmate5` varchar(255) default NULL,
`q9_yourchild_like_playmate5` enum('really_likes','likes','pretty_neutral','just_tolerates','refused_dontknow') default NULL,
`q10_like_yourchild_playmate5` enum('really_likes','likes','pretty_neutral','just_tolerates','refused_dontknow') default NULL,
`q11_getalong_playmate5` enum('very_well','okay','not_very_well','refused_dontknow') default NULL,
`q12_leading_play_playmate5` enum('my_child','playmate','both','adult','refused_dontknow') default NULL,
`q13_typical_playtone_playmate5` enum('positive','neutral','negative','refused_dontknow') default NULL,
`q14_typical_excitement_playmate5` enum('very_excited','active','calm','refused_dontknow') default NULL,
`q15_num_conflicts_playmate5` enum('frequently','occasionally','rarely','refused_dontknow') default NULL,
`q16_disruptive_playmate5` enum('ends_play','major_disruption','minor_disruption','no_disruption','refused_dontknow') default NULL,
`q17_how_involved_playmate5` enum('lot_of_interaction','stay_close_no_interaction','dont_stay_close_or_interact','refused_dontknow') default NULL,
`q18_arrangeplay_you_playmate5` varchar(255) default NULL,
`q18_arrangeplay_yourchild_playmate5` varchar(255) default NULL,
`q18_arrangeplay_other_playmate5` varchar(255) default NULL,
`q19_arrange_contacts_playmate5` enum('very_difficult','somewhat_difficult','not_difficult','refused_dontknow') default NULL,
`q20_stress_monitorplay_playmate5` enum('very_stressful','somewhat_stressful','not_stressful','refused_dontknow') default NULL,
`q21_facililate_getalong_playmate5` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_participate_activity_playmate5` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_maintain_presence_playmate5` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_outofview_listen_playmate5` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q21_outofview_notlisten_playmate5` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_manage_emotions_playmate5` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_understand_rules_playmate5` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_understand_howtoplay_playmate5` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_startplay_playmate5` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_remain_inplay_playmate5` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q22_manage_conflicts_playmate5` enum('frequently','occasionally','little_or_none','refused_dontknow') default NULL,
`q23_childin_school` enum('yes','no','refused_dontknow') default NULL,
`q24_childin_spneeds_school` enum('yes','no','refused_dontknow') default NULL,
`q25_school_numdays_perweek` varchar(255) default NULL,
`q26_school_numhrs_perday` varchar(255) default NULL,
`q27_numchildren_perclass` varchar(255) default NULL,
`q28_numchildren_specialneeds` varchar(255) default NULL,
`q29_childin_childcare` enum('yes','no','refused_dontknow') default NULL,
`q30_childin_spneeds_childcare` enum('yes','no','refused_dontknow') default NULL,
`q31_childcare_numdays_perweek` varchar(255) default NULL,
`q32_childcare_numhrs_perday` varchar(255) default NULL,
`q33_numchildren_perclass` varchar(255) default NULL,
`q35_numchildren_specialneeds` varchar(255) default NULL,
`activity_1` varchar(255) default NULL,
`activity_desc_1` enum('religious','play_group','sports','recreational','other','refused_dontknow') default NULL,
`activity_other1` varchar(255) default NULL,
`activity1_meet_permonth` varchar(255) default NULL,
`activity1_numchildren_participate` varchar(255) default NULL,
`activity1_numchildren_class` varchar(255) default NULL,
`activity1_numchildren_spneeds` varchar(255) default NULL,
`activity_2` varchar(255) default NULL,
`activity_desc_2` enum('religious','play_group','sports','recreational','other','refused_dontknow') default NULL,
`activity_other2` varchar(255) default NULL,
`activity2_meet_permonth` varchar(255) default NULL,
`activity2_numchildren_participate` varchar(255) default NULL,
`activity2_numchildren_class` varchar(255) default NULL,
`activity2_numchildren_spneeds` varchar(255) default NULL,
`activity_3` varchar(255) default NULL,
`activity_desc_3` enum('religious','play_group','sports','recreational','other','refused_dontknow') default NULL,
`activity_other3` varchar(255) default NULL,
`activity3_meet_permonth` varchar(255) default NULL,
`activity3_numchildren_participate` varchar(255) default NULL,
`activity3_numchildren_class` varchar(255) default NULL,
`activity3_numchildren_spneeds` varchar(255) default NULL,
`special_service_1` varchar(255) default NULL,
`special_service_desc_1` enum('occupational_physical','lang_speech','behavior','social_skills') default NULL,
`special_service1_meet_permonth` varchar(255) default NULL,
`special_service1_numchildren_participate` varchar(255) default NULL,
`special_service1_numchildren_class` varchar(255) default NULL,
`special_service_2` varchar(255) default NULL,
`special_service_desc_2` enum('occupational_physical','lang_speech','behavior','social_skills') default NULL,
`special_service2_meet_permonth` varchar(255) default NULL,
`special_service2_numchildren_participate` varchar(255) default NULL,
`special_service2_numchildren_class` varchar(255) default NULL,
`special_service_3` varchar(255) default NULL,
`special_service_desc_3` enum('occupational_physical','lang_speech','behavior','social_skills') default NULL,
`special_service3_meet_permonth` varchar(255) default NULL,
`special_service3_numchildren_participate` varchar(255) default NULL,
`special_service3_numchildren_class` varchar(255) default NULL,
PRIMARY KEY  (`CommentID`)

              );
INSERT INTO test_names(Test_name, Full_name,Sub_group) VALUES ('peer_socialcontact','Peer Contact Questionnaire',1);
INSERT INTO instrument_subtests(Test_name,Subtest_name,Description,Order_number) values ('peer_socialcontact','peer_socialcontact_page2','Peer Relationship', 1);
INSERT INTO instrument_subtests(Test_name,Subtest_name,Description,Order_number) values ('peer_socialcontact','peer_socialcontact_page3','Playmate #1', 2);
INSERT INTO instrument_subtests(Test_name,Subtest_name,Description,Order_number) values ('peer_socialcontact','peer_socialcontact_page4','Playmate #2', 3);
INSERT INTO instrument_subtests(Test_name,Subtest_name,Description,Order_number) values ('peer_socialcontact','peer_socialcontact_page5','Playmate #3', 4);
INSERT INTO instrument_subtests(Test_name,Subtest_name,Description,Order_number) values ('peer_socialcontact','peer_socialcontact_page6','Playmate #4', 5);
INSERT INTO instrument_subtests(Test_name,Subtest_name,Description,Order_number) values ('peer_socialcontact','peer_socialcontact_page7','Playmate #5', 6);
INSERT INTO instrument_subtests(Test_name,Subtest_name,Description,Order_number) values ('peer_socialcontact','peer_socialcontact_page8','Section 2', 7);
INSERT INTO instrument_subtests(Test_name,Subtest_name,Description,Order_number) values ('peer_socialcontact','peer_socialcontact_page9','Section 3', 8);
INSERT INTO instrument_subtests(Test_name,Subtest_name,Description,Order_number) values ('peer_socialcontact','peer_socialcontact_page10','Section 4', 9);
