CREATE TABLE `scq_subject` (
`CommentID` varchar(255) NOT NULL default '',

                          `UserID` varchar(255) default NULL,

                          `Examiner` varchar(255) default NULL,

                          `Testdate` timestamp(14) NOT NULL,

                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`score` varchar(255) default NULL,
`scq_diagnosis` varchar(255) default NULL,
`1_talk_short_phrases` enum('yes','no','not_answered') default NULL,
`2_to_and_fro` enum('yes','no','not_answered') default NULL,
`3_odd_phrases` enum('yes','no','not_answered') default NULL,
`4_socially_inappropriate` enum('yes','no','not_answered') default NULL,
`5_pronouns_mixed` enum('yes','no','not_answered') default NULL,
`6_words_invented` enum('yes','no','not_answered') default NULL,
`7_said_same_thing` enum('yes','no','not_answered') default NULL,
`8_particular_way` enum('yes','no','not_answered') default NULL,
`9_facial_expressions` enum('yes','no','not_answered') default NULL,
`10_hand_like_tool` enum('yes','no','not_answered') default NULL,
`11_interests_that_preoccupy` enum('yes','no','not_answered') default NULL,
`12_interested_in_parts` enum('yes','no','not_answered') default NULL,
`13_intense_interests` enum('yes','no','not_answered') default NULL,
`14_sight_feel_sound` enum('yes','no','not_answered') default NULL,
`15_mannerisms` enum('yes','no','not_answered') default NULL,
`16_complicated_movements` enum('yes','no','not_answered') default NULL,
`17_deliberate_injury` enum('yes','no','not_answered') default NULL,
`18_carry_objects` enum('yes','no','not_answered') default NULL,
`19_particular_friends` enum('yes','no','not_answered') default NULL,
`20_talk_friendly` enum('yes','no','not_answered') default NULL,
`21_spontaneously_copy` enum('yes','no','not_answered') default NULL,
`22_spontaneously_point` enum('yes','no','not_answered') default NULL,
`23_gestures` enum('yes','no','not_answered') default NULL,
`24_nod_yes` enum('yes','no','not_answered') default NULL,
`25_shake_no` enum('yes','no','not_answered') default NULL,
`26_look_directly` enum('yes','no','not_answered') default NULL,
`27_smile_back` enum('yes','no','not_answered') default NULL,
`28_show_things` enum('yes','no','not_answered') default NULL,
`29_offer_share` enum('yes','no','not_answered') default NULL,
`30_join_enjoyment` enum('yes','no','not_answered') default NULL,
`31_comfort` enum('yes','no','not_answered') default NULL,
`32_wanted_something` enum('yes','no','not_answered') default NULL,
`33_facial_expressions` enum('yes','no','not_answered') default NULL,
`34_spontaneously_join` enum('yes','no','not_answered') default NULL,
`35_play_pretend` enum('yes','no','not_answered') default NULL,
`36_seem_interested` enum('yes','no','not_answered') default NULL,
`37_respond_positively` enum('yes','no','not_answered') default NULL,
`38_came_into_room` enum('yes','no','not_answered') default NULL,
`39_play_imaginative` enum('yes','no','not_answered') default NULL,
`40_play_cooperatively` enum('yes','no','not_answered') default NULL,
PRIMARY KEY  (`CommentID`)

              ) TYPE=MyISAM;
