CREATE TABLE `scq_proband` (
`CommentID` varchar(255) NOT NULL default '',

                          `UserID` varchar(255) default NULL,

                          `Examiner` varchar(255) default NULL,

                          `Testdate` timestamp(14) NOT NULL,

                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`score` varchar(255) default NULL,
`scq_diagnosis` varchar(255) default NULL,
`q1_talk_short_phrases` enum('yes','no','not_answered') default NULL,
`q2_to_and_fro` enum('yes','no','not_answered') default NULL,
`q3_odd_phrases` enum('yes','no','not_answered') default NULL,
`q4_socially_inappropriate` enum('yes','no','not_answered') default NULL,
`q5_pronouns_mixed` enum('yes','no','not_answered') default NULL,
`q6_words_invented` enum('yes','no','not_answered') default NULL,
`q7_said_same_thing` enum('yes','no','not_answered') default NULL,
`q8_particular_way` enum('yes','no','not_answered') default NULL,
`q9_facial_expressions` enum('yes','no','not_answered') default NULL,
`q10_hand_like_tool` enum('yes','no','not_answered') default NULL,
`q11_interests_that_preoccupy` enum('yes','no','not_answered') default NULL,
`q12_interested_in_parts` enum('yes','no','not_answered') default NULL,
`q13_intense_interests` enum('yes','no','not_answered') default NULL,
`q14_sight_feel_sound` enum('yes','no','not_answered') default NULL,
`q15_mannerisms` enum('yes','no','not_answered') default NULL,
`q16_complicated_movements` enum('yes','no','not_answered') default NULL,
`q17_deliberate_injury` enum('yes','no','not_answered') default NULL,
`q18_carry_objects` enum('yes','no','not_answered') default NULL,
`q19_particular_friends` enum('yes','no','not_answered') default NULL,
`q20_talk_friendly` enum('yes','no','not_answered') default NULL,
`q21_spontaneously_copy` enum('yes','no','not_answered') default NULL,
`q22_spontaneously_point` enum('yes','no','not_answered') default NULL,
`q23_gestures` enum('yes','no','not_answered') default NULL,
`q24_nod_yes` enum('yes','no','not_answered') default NULL,
`q25_shake_no` enum('yes','no','not_answered') default NULL,
`q26_look_directly` enum('yes','no','not_answered') default NULL,
`q27_smile_back` enum('yes','no','not_answered') default NULL,
`q28_show_things` enum('yes','no','not_answered') default NULL,
`q29_offer_share` enum('yes','no','not_answered') default NULL,
`q30_join_enjoyment` enum('yes','no','not_answered') default NULL,
`q31_comfort` enum('yes','no','not_answered') default NULL,
`q32_wanted_something` enum('yes','no','not_answered') default NULL,
`q33_facial_expressions` enum('yes','no','not_answered') default NULL,
`q34_spontaneously_join` enum('yes','no','not_answered') default NULL,
`q35_play_pretend` enum('yes','no','not_answered') default NULL,
`q36_seem_interested` enum('yes','no','not_answered') default NULL,
`q37_respond_positively` enum('yes','no','not_answered') default NULL,
`q38_came_into_room` enum('yes','no','not_answered') default NULL,
`q39_play_imaginative` enum('yes','no','not_answered') default NULL,
`q40_play_cooperatively` enum('yes','no','not_answered') default NULL,
`textbox_test` varchar(255) default NULL,
`textbox_test_status` enum('not_answered') default NULL,
`textarea_test` text default NULL,
`textarea_test_status` enum('not_answered') default NULL,
`multiselect_test` varchar(255) default NULL,
`date_test_date` date default NULL,
`date_test_date_status` enum('not_answered') default NULL,
PRIMARY KEY  (`CommentID`)

              );
