CREATE TABLE `SRS2_InformantReport` (
`CommentID` varchar(255) NOT NULL default '',

                          `UserID` varchar(255) default NULL,

                          `Examiner` varchar(255) default NULL,

                          `Testdate` timestamp NOT NULL,

                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`respondent_age` varchar(255) default NULL,
`respondent_gender` enum('male','female') default NULL,
`informant` enum('mother','father','other_relative','spouse','other') default NULL,
`informant_other` varchar(255) default NULL,
`q1_uncomfortable_socialsituations` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q2_wrong_facialexpressions` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q3_self_confident` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q4_rigid_inflexible` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q5_others_take_advantage` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q6_rather_be_alone` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q7_aware_others_feeling` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q8_behave_strange_bizzare` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q9_overly_dependent` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q10_takethings_literally` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q11_have_selfconfidence` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q12_communicate_toothers` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q13_awkward_turn_takingtalk` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q14_notwell_coordinated` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q15_changefacialexp_understandmeaning` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q16_avoideyecontact` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q17_recognize_unfair` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q18_difficulty_makingfriends` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q19_frustrated_converyingideas` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q20_unusual_interests` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q21_imitate_actionsexpressions` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q22_interact_appropriately` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q23_joingroups_activities` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q24_diff_changeroutine` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q25_diff_wavelength` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q26_offer_comfort` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q27_avoid_socialinteractions` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q28_think_overandover` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q29_odd_weird` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q30_upset_situations` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q31_cant_getmind_off` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q32_good_personal_hygiene` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q33_socially_awkward` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q34_avoid_emotionallyclose` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q35_trouble_keepingup` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q36_difficulty_relating_family` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q37_difficulty_relating_adults` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q38_respond_moodchange` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q39_interested_toofew_topics` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q40_imaginative` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q41_wander_aimlessly` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q42_overly_sensitive` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q43_enjoy_smalltalk` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q44_touble_chains_causation` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q45_pay_attention` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q46_serious_facialexp` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q47_laugh_inappropriarte` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q48_goodsense_humor` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q49_wellat_intellectualtasks` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q50_repetitive_behavior` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q51_diff_directqstn` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q52_overly_loud` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q53_monotone_voice` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q54_thinkpeople_as_objects` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q55_invade_personalspace` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q56_walk_btwn_people` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q57_isolate_myself` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q58_concentrateon_parts` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q59_suspicious_ofpeople` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q60_emotionally_distant` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q61_infelxible` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q62_reason_unusual` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q63_greeting_unusual` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q64_tense_socialsitations` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
`q65_staring_gazing` enum('1_not_true','2_sometimes_true','3_often_true','4_almost_always_true','refused_dontknow') default NULL,
PRIMARY KEY  (`CommentID`)

              );
INSERT INTO test_names(Test_name, Full_name,Sub_group,isDirectEntry) VALUES ('SRS2_InformantReport','SRS2 Informant Report',1, true);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('SRS2_InformantReport','SRS2_InformantReport_page2','Informant Report Page2', 1);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('SRS2_InformantReport','SRS2_InformantReport_page3','Informant Report Page3', 2);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('SRS2_InformantReport','SRS2_InformantReport_page4','Informant Report Page4', 3);
