CREATE TABLE `tsi` (
`CommentID` varchar(255) NOT NULL default '',

                          `UserID` varchar(255) default NULL,

                          `Examiner` varchar(255) default NULL,

                          `Testdate` timestamp(14) NOT NULL,

                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`typical_or_asd_subject` enum('typical','asd','not_answered') default NULL,
`neurological_problems_proband` enum('yes','no','not_answered') default NULL,
`genetic_conditions_proband` enum('yes','no','not_answered') default NULL,
`seizures_disorders` enum('yes','no','not_answered') default NULL,
`relative_with_disorder` enum('yes','no','not_answered') default NULL,
`cns` enum('yes','no','not_answered') default NULL,
`tested_for_fragile_x` enum('yes','no','not_answered') default NULL,
`asd_further_information` text default NULL,
`asd_further_information_status` enum('not_answered') default NULL,
`relative_with_asd` enum('yes','no','not_answered') default NULL,
`neurological_problems_subject` enum('yes','no','not_answered') default NULL,
`genetic_conditions_subject` enum('yes','no','not_answered') default NULL,
`seizures_or_neuro_disorder` enum('yes','no','not_answered') default NULL,
`cns_problems` enum('yes','no','not_answered') default NULL,
`congenital_heart_problems` enum('yes','no','not_answered') default NULL,
`hearing_vision_impairments` enum('yes','no','not_answered') default NULL,
`diabetes` enum('yes','no','not_answered') default NULL,
`premature_birth` enum('yes','no','not_answered') default NULL,
`low_birth_weight` enum('yes','no','not_answered') default NULL,
`delivery_problems` enum('yes','no','not_answered') default NULL,
`in_utero_exposure` enum('yes','no','not_answered') default NULL,
`in_utero_substance` varchar(255) default NULL,
`in_utero_substance_status` enum('not_answered') default NULL,
`in_utero_substance_amount` varchar(255) default NULL,
`in_utero_substance_amount_status` enum('not_answered') default NULL,
`in_utero_time_exposure` varchar(255) default NULL,
`in_utero_time_exposure_status` enum('not_answered') default NULL,
`further_information` text default NULL,
`further_information_status` enum('not_answered') default NULL,
`med_his_q_1_med_surgical_problems` enum('yes','no','not_answered') default NULL,
`med_his_q_2_hospitalized` enum('yes','no','not_answered') default NULL,
`med_his_q_3_surgery` enum('yes','no','not_answered') default NULL,
`med_his_q_3_surgery_describe` varchar(255) default NULL,
`med_his_q_3_surgery_describe_status` enum('not_answered') default NULL,
`med_his_q_4_metal` enum('yes','no','not_answered') default NULL,
`med_his_q_5_medications` enum('yes','no','not_answered') default NULL,
`med_his_q_5_medications_describe` varchar(255) default NULL,
`med_his_q_5_medications_describe_status` enum('not_answered') default NULL,
`med_his_q_6_allergies` enum('yes','no','not_answered') default NULL,
`med_his_q_6_allergies_describe` varchar(255) default NULL,
`med_his_q_6_allergies_describe_status` enum('not_answered') default NULL,
`med_his_q_7_doctor` enum('yes','no','not_answered') default NULL,
`med_his_q_8_brain_MRI` enum('yes','no','not_answered') default NULL,
`med_his_q_8_brain_MRI_results` varchar(255) default NULL,
`med_his_q_8_brain_MRI_results_status` enum('not_answered') default NULL,
`med_his_q_9_anethesia` enum('yes','no','not_answered') default NULL,
`med_his_q_9_anethesia_problems` varchar(255) default NULL,
`med_his_q_9_anethesia_problems_status` enum('not_answered') default NULL,
`med_his_q_10_nap` varchar(255) default NULL,
`med_his_q_10_nap_status` enum('not_answered') default NULL,
`med_his_q_11_nap_how_long` varchar(255) default NULL,
`med_his_q_11_nap_how_long_status` enum('not_answered') default NULL,
`med_his_q_12_likelihood_sleep` enum('1','2','3','4','5','6','7','8','9','10','not_answered') default NULL,
`exc_inc_meets_criteria` enum('yes','no','not_answered') default NULL,
`exc_inc_contraindication` enum('yes','no','not_answered') default NULL,
`disposition` enum('yes','no','not_answered') default NULL,
PRIMARY KEY  (`CommentID`)

              ) TYPE=MyISAM;
